# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  
job:
  chdir: True

# output directory, generated dynamically on each run
run:
  dir: ${paths.output_dir}
sweep:
  dir: ${paths.output_dir}
  subdir: ${hydra.job.num}
