_target_: dl_toolbox.modules.supervised.Supervised

class_weights: [0., 1., 1., 1., 1., 1., 1.]
num_classes: 7
mixup: 0.

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.001
  weight_decay: 0.0

network:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: efficientnet-b0
  encoder_weights: imagenet
  in_channels: 3
  classes: 7
